<?php

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Bold\CheckoutPaymentBooster\ViewModel\ExpressPay;

/** @var Template $block */

/** @var ExpressPay $expressPayViewModel */
$expressPayViewModel = $block->getData('express_pay_view_model');
$pageSource = $block->getData('render_page_source');
$isEnabled = $expressPayViewModel->isEnabled($pageSource);
$containerId = 'express-pay-buttons-' . $pageSource;

if (!$isEnabled):
    return;
endif;
?>

<div id="express-pay-container" data-testid="express-pay-container">
    <div id="<?= $block->escapeHtmlAttr($containerId) ?>"></div>
</div>

<script>
    if (!window.checkoutConfig) {
        var layout = <?= $expressPayViewModel->getJsLayout() ?>;

        window.checkoutConfig = {};
        Object.assign(window.checkoutConfig, layout.checkoutConfig);
    }
</script>

<script type="text/x-magento-init">
{
    "#express-pay-container": {
        "Bold_CheckoutPaymentBooster/js/express-pay-storefront": {
            "pageSource": "<?= $block->escapeJs($pageSource) ?>",
            "containerId": "<?= $block->escapeJs($containerId) ?>"
        }
    }
}
</script>
