<?php

declare(strict_types=1);

?>
<div id="express-pay-container-cart" data-testid="express-pay-container-cart">
    <div id="express-pay-buttons-cart"></div>
</div>

<script type="text/x-magento-init">
    {
        "#express-pay-container-cart": {
            "Bold_CheckoutPaymentBooster/js/express-pay-storefront": {
                "pageSource": "cart",
                "containerId": "express-pay-buttons-cart"
            }
        }
    }
</script>
