<?php

declare(strict_types=1);

?>
<div id="express-pay-container-minicart" data-testid="express-pay-container-minicart">
    <div id="express-pay-buttons-minicart"></div>
</div>

<script type="text/x-magento-init">
    {
        "#express-pay-container-minicart": {
            "Bold_CheckoutPaymentBooster/js/express-pay-storefront": {
                "pageSource": "mini-cart",
                "containerId": "express-pay-buttons-minicart"
            }
        }
    }
</script>
