<?php

declare(strict_types=1);

?>
<div id="express-pay-container-product" data-testid="express-pay-container-product">
    <div id="express-pay-buttons-product-details"></div>
</div>

<script type="text/x-magento-init">
    {
        "#express-pay-container-product": {
            "Bold_CheckoutPaymentBooster/js/express-pay-storefront": {
                "pageSource": "product-details",
                "containerId": "express-pay-buttons-product-details"
            }
        }
    }
</script>
