<?php

declare(strict_types=1);

use Bold\CheckoutPaymentBooster\ViewModel\ExpressPay;
use Magento\Framework\View\Element\Template;

/** @var Template $block */

/** @var ExpressPay $expressPayViewModel */
$expressPayViewModel = $block->getData('express_pay_view_model');
$isCustomerLoggedIn = $expressPayViewModel->isCustomerLoggedIn();
$customerData = $expressPayViewModel->getCustomerData();
$isVirtualQuote = $expressPayViewModel->isVirtualQuote();
?>
<div id="express-pay-container-minicart" data-testid="express-pay-container-minicart">
    <div id="express-pay-buttons-minicart"></div>
</div>

<script>
    if (!window.hasOwnProperty('checkoutConfig')) {
        window.checkoutConfig = {
            quoteData: {
            },
        };
    }

    if (!window.hasOwnProperty('isCustomerLoggedIn')) {
        window.isCustomerLoggedIn = <?= /* @noEscape */ json_encode($isCustomerLoggedIn) ?>;
    }

    if (!window.hasOwnProperty('customerData')) {
        window.customerData = <?= /* @noEscape */ json_encode($customerData) ?>;
    }
</script>
<div id="express-pay-buttons-mini-cart"
     data-container-id="express-pay-buttons-mini-cart"
     data-page-source="mini-cart"
     data-is-virtual="<?= (int) $isVirtualQuote ?>"></div>
<script type="text/x-magento-init">
    {
        "#express-pay-container-minicart": {
            "Bold_CheckoutPaymentBooster/js/express-pay-storefront": {
                "pageSource": "mini-cart",
                "containerId": "express-pay-buttons-minicart"
            }
        }
    }
</script>
