name: Code Quality Checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  php-code-setup:
    name: Check PHP Code Quality
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
        tools: composer, cs2pr
        extensions: bcmath, gd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMPOSER_AUTH_JSON: ${{ secrets.COMPOSER_AUTH_JSON }}

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php

    - name: add magento credsentials
      run: composer config --global http-basic.repo.magento.com ${{ secrets.COMPOSER_MAGENTO_USERNAME }} ${{ secrets.COMPOSER_MAGENTO_PASSWORD }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

  run-parallel-lint:
    needs: php-code-setup
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php

    - name: Setup PHP 8.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
        tools: composer, cs2pr
        extensions: bcmath, gd

    - name: Check syntax
      run: vendor/bin/parallel-lint --checkstyle --exclude .git --exclude vendor .  | cs2pr
    
  run-phpcs:
    needs: run-parallel-lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php

    - name: Setup PHP 8.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
        tools: composer, cs2pr
        extensions: bcmath, gd

    - name: Detect coding standard violations
      run: vendor/bin/phpcs -q --report=checkstyle | cs2pr --graceful-warnings

  run-phpstan:
    needs: run-parallel-lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php

    - name: Setup PHP 8.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
        tools: composer, cs2pr
        extensions: bcmath, gd

    - name: Analyze code for potential bugs
      run: vendor/bin/phpstan analyse
